### ISSUE TITLE
HPC error with GPU

### ISSUE THREAD

**Issue by crypotex** [mt2017-tartu-shared-task/nmt-system-B#3]
[8-train-sockeye-rnn-cov.txt](https://github.com/mt2017-tartu-shared-task/nmt-system-B/files/1487863/8-train-sockeye-rnn-cov.txt)

[slurm-2676079.out.txt](https://github.com/mt2017-tartu-shared-task/nmt-system-B/files/1487865/slurm-2676079.out.txt)

Basically put up my slurm script and slurm output, not sure why it got aborted/cancelled... Seemed to be working at the start and then died. Seems like some GPU error. I contacted HPC center support.

**Comment by MaksymDel** [comment]
Did you install sockeye locally or use it from python-3.6.0 package?

**Comment by crypotex** [comment]
I used it from python-3.6.0

**Comment by crypotex** [comment]
Email from HPC center...

Hello,
Sorry, I am not familiar with sockeye, but this kind of error usually happens when a job tries to use a GPU that is not allocated for that job.
This is most easily fixed by choosing a GPU to use in the beginning of the python file.
You can tell it to use GPU 0, because the queue system always sets your first allocated GPU as GPU 0, second as GPU 1 etc. Even if they're actually GPU-s 7 and 8 for an example.
Sadly I do not know how to do it with sockeye.
Best regards,

But I am also surprised by this, because I thought sockeye does take first GPU available. Maksym any idea how to fix this or force this ? I didn't see a flag to specify some concrete gpu ...

**Comment by MaksymDel** [comment]
Hi,

here is info about GPU flags from their user documentation guide:
https://github.com/awslabs/sockeye/blob/429f34feaa215b6415fa33a9fc152cd56063d956/docs/user_documentation.md#cpugpu-training

**Comment by crypotex** [comment]
Solved after just re submitting same job ...
