### ISSUE TITLE
sockeye translate error - wierd versin issue ?!?

### ISSUE THREAD

**Issue by crypotex** [mt2017-tartu-shared-task/nmt-system-B#4]
Basically I cannot translate with sockeye, I get this following error: 
Started translation

sockeye.utils.SockeyeError: Given major version (1.8.3) does not match major code version (1.13.0)
Job done

In slurm script I use the same python module. 

More detailed in the files ... 

[slurm-2683511.out.txt](https://github.com/mt2017-tartu-shared-task/nmt-system-B/files/1501964/slurm-2683511.out.txt)

[9-sockeye-translate-rnn-cov.sh.txt](https://github.com/mt2017-tartu-shared-task/nmt-system-B/files/1501965/9-sockeye-translate-rnn-cov.sh.txt)

**Comment by crypotex** [comment]
Only reasonable explanation could be if python3-6 was update between training and translating, which was less than 24 hours apart ....

**Comment by MaksymDel** [comment]
I contacted HPC support to figure out the way they update packages. As a hotfix you can try to download needed version of sockeye and translate with it locally:
https://github.com/awslabs/sockeye/releases

**Comment by MaksymDel** [comment]
Someone requested Sockeye update yesterday and it was updated. This caused the issue. Do you think we need to downgrade sockeye back?
